-- =========================================
-- AMAZON E-COMMERCE BUSINESS ANALYSIS
-- =========================================

-- 1. Total Revenue
-- 2. Total Orders
-- 3. Top 10 Products by Revenue
-- 4. Category-wise Revenue
-- 5. Top Customers by Spending
-- 6. Delivery Status Analysis
-- 7. Cancelled Orders
-- 8. Return Rate
-- 9. Payment Method Performance
-- 10. Channel-wise Sales
-- 11. Monthly Revenue Trend
-- 12. Best-performing Category
-- 13. Average Order Value (AOV)
-- 14. Most Returned Products
-- 15. State/City-wise Customer Analysis


-- 1. Calculate the total revenue generated from all orders

SELECT 
    SUM(LineTotal) AS Total_Revenue
FROM OrderItems;

-- Q2. Total number of orders
SELECT 
    COUNT(*) AS total_orders
FROM orders;

-- Q3. Find the top 10 products by total revenue
-- We join Products with OrderItems using ProductID
-- and calculate revenue by summing LineTotal for each product.

SELECT
    p.ProductID,
    p.ProductName,
    SUM(oi.LineTotal) AS Total_Revenue
FROM Products p

INNER JOIN OrderItems oi
    ON p.ProductID = oi.ProductID

GROUP BY
    p.ProductID,
    p.ProductName

ORDER BY
    Total_Revenue DESC

LIMIT 10;


-- Q4. Calculate total revenue generated by each product category
-- Products contains the category information.
-- OrderItems contains the revenue (LineTotal).
-- We join both tables using ProductID and aggregate revenue by category.

SELECT
    p.Category,
    SUM(oi.LineTotal) AS Total_Revenue
FROM Products p

INNER JOIN OrderItems oi
    ON p.ProductID = oi.ProductID

GROUP BY
    p.Category

ORDER BY
    Total_Revenue DESC;



-- Q5. Find the top 10 customers by total spending
-- Customers provides customer information.
-- Orders connects customers with their orders.
-- OrderItems provides the revenue generated by each order.
-- We calculate total spending for each customer and rank them from highest to lowest.

SELECT
    c.CustomerID,
    CONCAT(c.FirstName, ' ', c.LastName) AS Customer_Name,
    SUM(oi.LineTotal) AS Total_Spending
FROM Customers c

INNER JOIN Orders o
    ON c.CustomerID = o.CustomerID

INNER JOIN OrderItems oi
    ON o.OrderID = oi.OrderID

GROUP BY
    c.CustomerID,
    c.FirstName,
    c.LastName

ORDER BY
    Total_Spending DESC

LIMIT 10;



-- Q6. Analyze the distribution of orders by delivery status
-- Shipments contains the delivery status for each order.
-- We group orders by DeliveryStatus and count the number of shipments
-- in each status.

SELECT
    DeliveryStatus,
    COUNT(*) AS Total_Shipments
FROM Shipments

GROUP BY
    DeliveryStatus

ORDER BY
    Total_Shipments DESC;



-- Q7. Calculate the total number of cancelled orders
-- The Orders table contains the order status.
-- We filter the orders where Status is 'Cancelled'
-- and count the number of cancelled orders.

SELECT
    COUNT(*) AS Cancelled_Orders
FROM Orders
WHERE Status = 'Cancelled';




-- Q8. Calculate the overall order return rate
-- We count distinct orders that have at least one return.
-- DISTINCT is important because an order can contain multiple returned products.
-- Return Rate = Returned Orders / Total Orders × 100

SELECT
    ROUND(
        COUNT(DISTINCT r.OrderID) * 100.0
        / (SELECT COUNT(*) FROM Orders),
        2
    ) AS Return_Rate_Percentage
FROM Returns r;




-- Q9. Analyze payment method performance
-- We group payments by payment method and calculate:
-- 1. Total number of payments
-- 2. Total payment amount
-- 3. Average payment amount
--
-- This helps identify the most frequently used and
-- highest-value payment methods.

SELECT
    Method AS Payment_Method,
    COUNT(*) AS Total_Payments,
    ROUND(SUM(Amount), 2) AS Total_Payment_Amount,
    ROUND(AVG(Amount), 2) AS Average_Payment_Amount

FROM Payments

GROUP BY
    Method

ORDER BY
    Total_Payment_Amount DESC;






-- Q10. Analyze sales performance by order channel
-- Orders contains the sales channel used for each order.
-- OrderItems contains the revenue generated by each order item.
-- We join both tables using OrderID and calculate:
-- 1. Total number of orders
-- 2. Total revenue
-- 3. Average revenue per order
--
-- This helps compare the performance of different sales channels.

SELECT
    o.Channel AS Sales_Channel,
    COUNT(DISTINCT o.OrderID) AS Total_Orders,
    ROUND(SUM(oi.LineTotal), 2) AS Total_Revenue,
    ROUND(
        SUM(oi.LineTotal) / COUNT(DISTINCT o.OrderID),
        2
    ) AS Average_Revenue_Per_Order

FROM Orders o

INNER JOIN OrderItems oi
    ON o.OrderID = oi.OrderID

GROUP BY
    o.Channel

ORDER BY
    Total_Revenue DESC;




-- Q11. Calculate monthly revenue trend
-- Orders contains the order date.
-- OrderItems contains the revenue generated from each order.
-- We join both tables using OrderID and group the revenue by month.
-- This helps identify monthly sales trends and seasonal patterns.

SELECT
    DATE_FORMAT(o.OrderDate, '%Y-%m') AS Order_Month,
    ROUND(SUM(oi.LineTotal), 2) AS Monthly_Revenue

FROM Orders o

INNER JOIN OrderItems oi
    ON o.OrderID = oi.OrderID

GROUP BY
    DATE_FORMAT(o.OrderDate, '%Y-%m')

ORDER BY
    Order_Month;




-- Q12. Identify the best-performing product category
-- Products contains the category information.
-- OrderItems contains the revenue generated by each product.
-- We calculate total revenue for each category,
-- sort the categories from highest to lowest revenue,
-- and return the top-performing category.

SELECT
    p.Category,
    ROUND(SUM(oi.LineTotal), 2) AS Total_Revenue

FROM Products p

INNER JOIN OrderItems oi
    ON p.ProductID = oi.ProductID

GROUP BY
    p.Category

ORDER BY
    Total_Revenue DESC

LIMIT 1;




-- Q13. Calculate the Average Order Value (AOV)
-- AOV represents the average revenue generated per order.
-- Formula:
-- AOV = Total Revenue / Total Number of Orders
--
-- DISTINCT OrderID is used because one order can contain
-- multiple items and therefore multiple rows in OrderItems.

SELECT
    ROUND(
        SUM(LineTotal) / COUNT(DISTINCT OrderID),
        2
    ) AS Average_Order_Value

FROM OrderItems;




-- Q14. Identify the most returned products
-- Returns contains information about returned products.
-- Products provides the product name and category.
-- We count the number of returns for each product
-- and rank them from highest to lowest.

SELECT
    p.ProductID,
    p.ProductName,
    p.Category,
    COUNT(*) AS Total_Returns

FROM Returns r

INNER JOIN Products p
    ON r.ProductID = p.ProductID

GROUP BY
    p.ProductID,
    p.ProductName,
    p.Category

ORDER BY
    Total_Returns DESC

LIMIT 10;